# ICP Assignment-3
CS 5720 Neural Network & Deep Learning
700735513, Satya Ishyanth Kadali

In [ ]:
Question 1

In [2]:
#creating a Employee class
class Employee:
    total_salary = 0
    emp_count = 0
    
    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        # increment total salary and employee count
        Employee.total_salary += salary
        Employee.emp_count += 1
        
    # class method to calculate average salary
    @classmethod
    def average_salary(cls):
        return cls.total_salary / cls.emp_count

#Creating a Fulltime Employee class with Inheritence 
class FulltimeEmployee(Employee):
    pass

# creating instances of the classes
emp1 = FulltimeEmployee("Ishyanth", "Kadali", 90000, "Research")
emp2 = Employee("Abhi", "Tammana", 40000, "Customer Service")
emp3 = Employee("Jayakar", "Dadala", 80000, "Accounting")

print("Average Salary = ", Employee.average_salary())
print("Number of Employees = ", Employee.emp_count)


Average Salary =  70000.0
Number of Employees =  3


Question 2

In [6]:
import numpy as np

# Creating a random vector of size 20 with only float values in the range 1-20
r_vector = np.random.uniform(1, 20, 20)

# Reshape the array to 4x5
new_array = r_vector.reshape(4, 5)

# Replace the max in each row with 0 (axis=1)
np.place(new_array, new_array == np.max(new_array, axis=1, keepdims=True), 0)

print(new_array)

[[ 0.          7.22182483 12.85463727 11.54550355  3.78727794]
 [ 0.         10.75728244 10.07139048  7.32120781 12.60012389]
 [ 5.68009521  3.55195525  3.99239713  0.          4.95695426]
 [14.13367363  0.          9.95311926 13.16701456 16.06566808]]
